#!/usr/bin/env bash
# This script connects to a remote server and secure transfer a file from our client to remote server

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

scp -o "StrictHostKeyChecking=no" -i "$KEY" "$FILE" "$USER"@"$IP":~
