#!/usr/bin/env bash
#Bash script to reload Gunicorn in a graceful way

# Send a HUP signal to the gunicorn Master processes
# (ie those with a parent process ID of 1)
pkill --signal HUP --parent 1 gunicorn
